### ISSUE TITLE
Connection scheme

### ISSUE THREAD

**Issue by Diddlik** [alessandromatera/SDM230-emulator-growatt-esp-mqtt#1]
Hi, I am currently using the self-designed stick (https://github.com/Diddlik/USB_Dongle_ESP8266_Max485) to read out Growatt with ESPHOME. 
The next step is to make the export limit.
Could you roughly sketch how your scheme looks like how to connect everything?

**Comment by alessandromatera** [comment]
Hi @Diddlik, here's the schematic
https://github.com/alessandromatera/SDM230-emulator-growatt-esp-mqtt/raw/main/Connections.png

I powered the system with the USB port of the inverter.

I hope it helps

**Comment by Diddlik** [comment]
@alessandromatera  And how do you read a values from Growatt? The seconde one esp connected to pin 3/4?

**Comment by alessandromatera** [comment]
@Diddlik I actually use another ESP8266 device which is connected directly through the USB port, which also powers the other ESP I use for the power limitation functions.
For readings I used this repo: https://github.com/otti/Growatt_ShineWiFi-S

I think that I could use the same device which reads from USB and controls the power limitation through RS485.

If you want to use the RS485 protocol also for the reading part, since - at least in my growatt inverter - there are two different 485 ports for readings (pins 3 and 4) and for the SDM230 meter (pins 7 and 8), you should get two different RS485-TTL converters connected to different ESP pins.

**Comment by alessandromatera** [comment]
@Diddlik Also, in the case you want to read from RS485, remember that for the reading ports your ESP behaves as a master and the Growatt as Slave, meanwhile for the Power Limitation Functions, The growatt is the master and the ESP is the slave.

**Comment by Diddlik** [comment]
> @Diddlik I actually use another ESP8266 device which is connected directly through the USB port, which also powers the other ESP I use for the power limitation functions. For readings I used this repo: https://github.com/otti/Growatt_ShineWiFi-S
> 
> I think that I could use the same device which reads from USB and controls the power limitation through RS485.
> 
> If you want to use the RS485 protocol also for the reading part, since - at least in my growatt inverter - there are two different 485 ports for readings (pins 3 and 4) and for the SDM230 meter (pins 7 and 8), you should get two different RS485-TTL converters connected to different ESP pins.

Ok, thank you for quick reply. It seems, in all cases I need to use two devices. One for reading (USB from Growatt or RS485 from Pin 3/4) and one for Limitation (pin 7/8). So, it is time to design a new device, that can handle it. Best case:
1. ESP perform reading from growatt (usb or RS485 Converter)
2. The same ESP perform as Power Meter and set the limitation over the second ES485 Converter

**Comment by alessandromatera** [comment]
Great! keep me posted!
