### ISSUE TITLE
To Growatt One SDM630 over Mqtt to 0 ?

### ISSUE THREAD

**Issue by Woogel** [alessandromatera/SDM230-emulator-growatt-esp-mqtt#2]
Hello, and first of all, a big thumbs up for your project. My question: Can the SDM630 be read using an ESP8266 or ESP32 and then sent as MQTT to IOBroker? Afterward, can two Growatt WR units read the data via Wi-Fi using ESP8266 or ESP32 in a way that makes them think they are actually receiving the data directly from the SDM630 and adjust their performance for zero feed-in? One WR unit is in the garage, and the second one is in the pool house.

Thanks 
Edgar

**Comment by alessandromatera** [comment]
Ciao Woogel, thanks for the thumbs up! In regards to your question, I think that would be possible to have an ESP device connected to the SDM630 that reads the values and streams it to an Mqtt broker. I saw many project on github with this purpose. Then you can use my code to feed these readings to your Growatt inverter. 

My doubt is: how the two inverter will manage the zero feed policy? which inverter will reduce/increase it's power first? Since the zero feed policy is not regulated from the ESP itself, but it's the inverter which modulates its power taking into account the readings from the SDM meater. I'm not sure this part would be easy.

**Comment by Woogel** [comment]
Hello Alessandromatera. I've souped up the code a bit with help from ChatGPT. I've set up a mini server running Docker with Node-RED, FTP, ioBroker, Grafana, and InfluxDB. I've configured an ESP to read data from my SDM630, send it to MQTT, and then Node-RED is set up to ingest and process the data. I'm summing it up and then sending it in a 1/3 to 2/3 ratio to MQTT under Energy/sdm630/nodered/restpower/1_3 and 2_3. Since each ESP has its own link to its data, the Growatt1000 gets the 1/3, and the 2000 gets the 2/3. Additionally, I've added an RGB LED for status display, an auto-update for firmware, and I'm still tinkering with the HTML output. Unfortunately, there's no sun at the moment for precise testing. Normal Deutsch.

**Comment by alessandromatera** [comment]
Hoping for the sun!

great work and Keep me posted!

**Comment by Diddlik** [comment]
I have at the moment a similar solution.
I read the current consumption, if it is negative, it is calculated per inverter how far it should be throttled.

**Comment by Woogel** [comment]
Hello, I have a big problem. Now that the sun is shining again, I have connected your Emu to my Growatt 2000 and 1000, and in both cases, the cloverleaf turns from green to red after a few seconds! I have measured the data line for continuity, and everything seems fine. What settings do I need to adjust on the Growatt besides the zero feed-in? When I connect the Growatt directly to an SDM630, everything is fine, but not with the EMU. What could be the issue? Thank you.
