### ISSUE TITLE
what to send over mqtt???

### ISSUE THREAD

**Issue by fvanriet** [alessandromatera/SDM230-emulator-growatt-esp-mqtt#3]
hello alessandro.
what do you send to the mqtt topic???
is it only a number or more????

and the topic , where you send the gridpower from the shellie to, is it

shellies/contatore/emeter/0/power

i have tried it butt cant get the growatt to respond.
connections on pin 7 en 8.

i have tested with an eastron sdm230 and the growatt works with that.

thanks in advance

**Comment by alessandromatera** [comment]
Hi fvanriet, I'm having trouble understanding your question.
In my case I have the following scheme:
1 shelly EM as a standalone device which shares the power reading from the grid via mqtt. To do so it is connected to a mqtt broker (in my case a raspberry pi). Basically the shelly is continuously broadcasting the power reading through mqtt with the topic that in my case is `shellies/contatore/emeter/0/power`. Take in mind that "_contatore_" is the name I gave to my shelly device. In your case should be `shellies/device_name/emeter/0/power`

Next I have an esp which is connected via RS485 to the growatt and via mqtt to the broker in order to get the grid readings.
So, the esp device get the power readings from the mqtt broker (following the same topic of the shelly device) and then forward the information through RS485 to the inverter.

Hope it helps.

**Comment by fvanriet** [comment]
hello alessandro,

i don't have a shellie. but if i send a number to the mqtt shellies/contatore/emeter/0/power , from another meter it schould work to?

i see the numbers comming in on the esp true serial.
but the growatt inverter doesn't react on the numbers i have send, he is not limmitting the power.

the esp rs485 is connected on the limmitting A en B from growatt.
where normally you connect the limmitting meter from eastron.

the schellies are they only sending a number like 220 for power consumption or do they send something else also.

i have tried to send power consumption true node red to the mqtt, from another meter but the growatt keeps putting way more power out.

so the question is what is the schellie sending after the "shellies/contatore/emeter/0/power" what is the payload and the type.
do you know that? 

already a great thanks for you're answer.
